stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compilando o projeto..."
    - npm install

test-job:
  stage: test
  script:
    - echo "Executando testes..."
    - npm test

deploy-job:
  stage: deploy
  script:
    - echo "Fazendo deploy..."
    - npm run deploy
  only:
    - main
